### ISSUE TITLE
Getting the best model

### ISSUE THREAD

**Issue by israel-cj** [automl/amltk#208]
Hi, there:) great work with this framework.
I wonder after optimizing and getting back the History() is there a way to call the best model found automatically? Thanks

**Comment by eddiebergman** [comment]
Hi @israel-cj,

Great question. I had something like that originally but I removed it for a few reasons I was unsure about.

Short answer:
```python
best_report: Trial.Report = max(history.reports, key=lambda report: report.metrics["xxx"]):

best_config = best_report.config
```

You may have noticed I used `max`, this is because there used to be no `Metric` definitions which there is now. For that reason, I could definelty implement a `best()` that uses the `Metric` definition.

There's still an issue that there's no defined best for when you have multiple metrics but I could throw an explicit error in that case.

**Comment by israel-cj** [comment]
Thanks @eddiebergman 
Yes, what I have done is a bit simpler, I followed your example thinking that the metric is `accuracy`:
`trace = (
      trial_history.sortby("accuracy")
  )

  best_model_id = 0 # They are sorted the best is the 0
  trace[best_model_id].config
  configured_pipeline = pipeline.configure(trace[best_model_id].config)
  best_model = configured_pipeline.build(builder="sklearn")`

**Comment by eddiebergman** [comment]
Please see #209 :)

Will be live soon

**Comment by israel-cj** [comment]
amazing, thanks man

**Comment by eddiebergman** [comment]
And it's up :) https://automl.github.io/amltk/1.6.0/api/amltk/optimization/history/#amltk.optimization.history.History.best

**Comment by israel-cj** [comment]
Thank you @eddiebergman , it was impressively fast
